# Generated by Django 3.2.8 on 2022-08-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='clientid',
        ),
    ]
