# Generated by Django 3.2.8 on 2022-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
